#!/usr/bin/env python

import sys 

from mininet.log import setLogLevel, info 
from mn_wifi.cli import CLI 
from mn_wifi.net import Mininet_wifi


def topology(args):

  net = Mininet_wifi()
  
  info("*** Creating nodes\n")
  h1 = net.addHost('h1', mac='00:00:00:00:00:01', ip='10.0.0.1/8')
  sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8', range='23')
  ap1 = net.addAccessPoint( 'ap1', ssid= 'ap1-ssid', mode= 'g', channel= '1', position='40,80,0', range='30')
  ap2 = net.addAccessPoint( 'ap2', ssid= 'ap2-ssid', mode= 'g', channel= '1', position='40,110,0', range='30')
  ap3 = net.addAccessPoint( 'ap3', ssid= 'ap3-ssid', mode= 'g', channel= '1', position='60,100,0', range='30')
  ap4 = net.addAccessPoint( 'ap4', ssid= 'ap4-ssid', mode= 'g', channel= '1', position='60,60,0', range='30')
  ap5 = net.addAccessPoint( 'ap5', ssid= 'ap5-ssid', mode= 'g', channel= '1', position='20,60,0', range='30')
  ap6 = net.addAccessPoint( 'ap6', ssid= 'ap6-ssid', mode= 'g', channel= '1', position='20,100,0', range='30')
  ap7 = net.addAccessPoint( 'ap7', ssid= 'ap7-ssid', mode= 'g', channel= '1', position='100,80,0', range='30')
  ap8 = net.addAccessPoint( 'ap8', ssid= 'ap8-ssid', mode= 'g', channel= '1', position='100,110,0', range='30')
  ap9 = net.addAccessPoint( 'ap9', ssid= 'ap9-ssid', mode= 'g', channel= '1', position='120,100,0', range='30')
  ap10 = net.addAccessPoint( 'ap10', ssid= 'ap10-ssid', mode= 'g', channel= '1', position='120,60,0', range='30')
  ap11 = net.addAccessPoint( 'ap11', ssid= 'ap11-ssid', mode= 'g', channel= '1', position='80,60,0', range='30')
  ap12 = net.addAccessPoint( 'ap12', ssid= 'ap12-ssid', mode= 'g', channel= '1', position='80,100,0', range='30')
  c1 = net.addController('c1')

  info("*** Configuring propagation model\n")
  net.setPropagationModel(model="logDistance", exp=4.5)

  info("*** Configuring wifi nodes\n")
  net.configureWifiNodes()
    
  info("*** Associating and Creating links\n")
  net.addLink(ap1,h1)
  net.addLink(ap2,h1)
  net.addLink(ap1,ap2)
  net.addLink(ap1,ap3)
  net.addLink(ap1,ap4)
  net.addLink(ap1,ap5)
  net.addLink(ap1,ap6)
  net.addLink(ap7,ap8)
  net.addLink(ap7,ap9)
  net.addLink(ap7,ap10)
  net.addLink(ap7,ap11)
  net.addLink(ap7,ap12)
  net.addLink(ap1,ap7)
    
  if '-p' not in args:
    net.plotGraph(max_x=160, max_y=160)
       
  net.startMobility(time=0, ac_method='ssf')
  net.mobility(sta1, 'start', time=20, position='40,80,0')
  net.mobility(sta1, 'stop', time=79, position='40,110,0')
  net.stopMobility(time=80)

  info("* Starting network\n")
  net.build()
  c1.start()
  ap1.start([c1])
  ap2.start([c1])
  ap3.start([c1])
  ap4.start([c1])
  ap5.start([c1])
  ap6.start([c1])
  ap7.start([c1])
  ap8.start([c1])
  ap9.start([c1])
  ap10.start([c1])
  ap11.start([c1])
  ap12.start([c1])

  info("* Running CLI\n")
  CLI(net)

  info("* Stopping network\n")
  net.stop()


if __name__ == '__main__':
  setLogLevel('info')
  topology(sys.argv)
